---
title: "Schedule"
format: 
  html:
    code-fold: false
    code-tools: false
editor: visual
---

::: {.callout-note appearance="minimal"}
## Day 1: 24th November 2024

Introduction to epidemiologic research and causal concepts, measures of disease association and interpretation

**Objective:** Understanding basic epidemiologic concepts and measures of disease association

**Session Chair:** [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)
:::

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                                                                                               | Presenter                                                                                                                                                                        |
+===============+=====================================================================================================================================================================================================================================+==================================================================================================================================================================================+
| 08:00 - 08:15 | Arrival and registration                                                                                                                                                                                                            | CEMA                                                                                                                                                                             |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:15 - 08:25 | Introduction and welcoming remarks                                                                                                                                                                                                  | CEMA                                                                                                                                                                             |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:25 - 08:30 | Goals, objectives and structure of the training                                                                                                                                                                                     | [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)                                                                                                |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:30 - 09:30 | Lecture: Epidemiology and our Health                                                                                                                                                                                                | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi)                                                                                          |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Lecture: Introduction to epidemiologic research and causal concepts                                                                                                                                                                 | [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)                                                                                                |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                                                                                        |                                                                                                                                                                                  |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 13:00 | [Lecture: Measures of disease association and interpretation](https://drive.google.com/file/d/1OJ1InVWVX0kA3c5tTc5bW1ndXs0nf3Pm/view?usp=share_link)                                                                                | [Paula Christen](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-paula-christen)                                                                                          |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                                                                                      |                                                                                                                                                                                  |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 16:30 | [Practical: Calculate and interpret measures of association (risk ratios, odds ratios, and attributable risk at stratum/population level)](https://drive.google.com/drive/folders/1l4SU1Ed8yedKfM1F75O6nhZSsmq-W4mN?usp=share_link) | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:30         | ☕ Tea break                                                                                                                                                                                                                        |                                                                                                                                                                                  |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 2: 25th November 2024

Epidemiological Study designs

**Objective:** Understanding epidemiological study designs and data analytics from different study designs

**Session Chair:** [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)
:::

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                                          | Presenter                                                                                                                                                                        |
+===============+================================================================================================================================================================================+==================================================================================================================================================================================+
| 08:00 - 08:30 | Arrival and registration                                                                                                                                                       | CEMA                                                                                                                                                                             |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:30 - 09:30 | Causal concepts in epidemiology                                                                                                                                                | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi)                                                                                          |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 09:30 - 10:30 | Lecture: Introduction to epidemiological study designs                                                                                                                         | [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)                                                                                             |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | Observational studies                                                                                                                                                          |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Cohort studies                                                                                                                                                             |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Case-control studies                                                                                                                                                       |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Cross-sectional surveys                                                                                                                                                    |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Routine-data-based studies: Individual level vs ecological studies)                                                                                                        |                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                                   |                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 12:00 | Lecture: Introduction to epidemiological study designs                                                                                                                         | [Joseph Nkuranga](https://cema-africa.uonbi.ac.ke/people/clinical-research/dr-joseph-nkuranga)                                                                                   |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | Intervention/Experimental studies                                                                                                                                              |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Clinical trials                                                                                                                                                            |                                                                                                                                                                                  |
|               |                                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Field trials                                                                                                                                                               |                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00 - 13:00 | Use of Epidemiological data for informed policy decisions                                                                                                                      | [Kahariri Samuel](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-samuel-kahariri)                                                                                        |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                                 |                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 16:30 | [Practical: Understand how to analyze and interpret data from various study designs.](https://drive.google.com/drive/folders/11Efv_TVXQT6g6aNBI_LT6qazHm7CIe_s?usp=share_link) | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:30         | ☕ Tea break                                                                                                                                                                   |                                                                                                                                                                                  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 3: 26th November 2024

Screening and Diagnostic Tests

**Objective:** Understanding attributes of diagnostic and screening tests and interpretation of test performance

**Session Chair:** Geoffrey Githinji
:::

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                    | Presenter                                                                                                                                                                        |
+===============+==========================================================================================================================================================+==================================================================================================================================================================================+
| 08:00 - 08:30 | Arrival and registration                                                                                                                                 | CEMA                                                                                                                                                                             |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:30 - 10:30 | [Lecture: Screening and Diagnostic Tests](https://drive.google.com/drive/folders/1V3hkdW42D7qiRPHW6N6AjfUMAkzOoNwq?usp=share_link)                       | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)                                                                                                       |
|               |                                                                                                                                                          |                                                                                                                                                                                  |
|               | -   Attributes of a test                                                                                                                                 |                                                                                                                                                                                  |
|               |                                                                                                                                                          |                                                                                                                                                                                  |
|               | -   Ability of a test to detect disease or health                                                                                                        |                                                                                                                                                                                  |
|               |                                                                                                                                                          |                                                                                                                                                                                  |
|               | -   Validity and reliability of diagnostic and screening tests.                                                                                          |                                                                                                                                                                                  |
|               |                                                                                                                                                          |                                                                                                                                                                                  |
|               | -   Sensitivity, specificity, positive predictive value, and negative predictive value.                                                                  |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                             |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 12:00 | [Lecture: Screening and Diagnostic Tests](https://drive.google.com/drive/folders/1V3hkdW42D7qiRPHW6N6AjfUMAkzOoNwq?usp=share_link)                       | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)                                                                                                       |
|               |                                                                                                                                                          |                                                                                                                                                                                  |
|               | -   Comparison of multiple tests in the absence of a gold standard                                                                                       |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00 - 13:00 | [Practical session – Calculating and interpreting test results](https://drive.google.com/drive/folders/1V3hkdW42D7qiRPHW6N6AjfUMAkzOoNwq?usp=share_link) | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                           |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 16:30 | [Practical: comparing performance of different tests](https://drive.google.com/drive/folders/1V3hkdW42D7qiRPHW6N6AjfUMAkzOoNwq?usp=share_link)           |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:30         | ☕ Tea break                                                                                                                                             |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 4: 27th November 2024

Sampling and Validity in epidemiological studies

**Objective:** Understanding sampling and validity in epidemiological research

**Session Chair:** George Paul
:::

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time          | Topic                                                                                                                                                          | Presenter                                                                                                                                                                        |
+===============+================================================================================================================================================================+==================================================================================================================================================================================+
| 08:00 - 08:30 | Arrival and registration                                                                                                                                       | CEMA                                                                                                                                                                             |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:30 - 10:30 | [Lecture:Sampling](https://docs.google.com/presentation/d/14VsKpPGYuDCKyPbpCU1_DmGKbnlZU6No/edit?usp=share_link&ouid=113648051799093918679&rtpof=true&sd=true) | Geoffrey Githinji                                                                                                                                                                |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Introduction to sampling                                                                                                                                   |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Non-probability sampling                                                                                                                                   |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Probability sampling                                                                                                                                       |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Simple random sampling                                                                                                                                     |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Systematic random sampling                                                                                                                                 |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Stratified random sampling                                                                                                                                 |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Cluster sampling                                                                                                                                           |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Multistage sampling                                                                                                                                        |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                   |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 12:00 | Practical: Sampling                                                                                                                                            | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Sampling error and bias                                                                                                                                    |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00 - 13:00 | Practical: Practical session – Calculating and interpreting test results                                                                                       | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                 |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:00 | Lecture: Validity in epidemiological studies                                                                                                                   | [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)                                                                                                |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Introduction to  bias, confounding, and effect modification in epidemiological studies                                                                     |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   Strategies for controlling bias, and confounding.                                                                                                          |                                                                                                                                                                                  |
|               |                                                                                                                                                                |                                                                                                                                                                                  |
|               | -   The concept of interactions.                                                                                                                               |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:00 - 16:30 | Practical: Bias                                                                                                                                                | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema) |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:30         | ☕ Tea break                                                                                                                                                   |                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

::: {.callout-note appearance="minimal"}
## Day 5: 28th November 2024

Introduction to correlation and regression analysis in epidemiology

**Objective:** understanding correlation and regression analysis in epidemiologic research

**Session Chair:** [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema)
:::

+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time          | Topic                                                                            | Presenter                                                                                                                                                                                                                                                                 |
+===============+==================================================================================+===========================================================================================================================================================================================================================================================================+
| 08:00 - 08:30 | Arrival and registration                                                         | CEMA                                                                                                                                                                                                                                                                      |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08:30 - 10:30 | Lecture: Introduction to correlation and regression analysis in epidemiology     | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi)                                                                                                                                                                                   |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:30 - 11:00 | ☕ Tea break                                                                     |                                                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 12:00 | **Lecture:** Introduction to correlation and regression analysis in epidemiology | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)                                                                                                                                                                                                |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00 - 13:00 | **Practical:** Describe the process for and create                               | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema), [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi) |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Pearson correlation coefficient                                              |                                                                                                                                                                                                                                                                           |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Simple linear regression                                                     |                                                                                                                                                                                                                                                                           |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Multiple linear regression                                                   |                                                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13:00 - 14:00 | 🍲 Lunch break                                                                   |                                                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 16:30 | **Practical:** Describe the process for and create                               | [George Paul](https://globalhealthcenter.umn.edu/staff/george-omondi-paul), Githinji Geoffrey, [Mulei Muema](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-mulei-muema), [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi) |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Logistic regression                                                          |                                                                                                                                                                                                                                                                           |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Mixed effects/hierarchical models.                                           |                                                                                                                                                                                                                                                                           |
|               |                                                                                  |                                                                                                                                                                                                                                                                           |
|               | -   Analysis of correlated data.                                                 |                                                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16:30 - 17:00 | Closure and next steps                                                           | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi)                                                                                                                                                                                   |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17:00         | ☕ Tea break                                                                     |                                                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
